import type { Metadata } from "next";
import Script from "next/script";
import GoogleAnalyticsTracker from "@/components/GoogleAnalyticsTracker";
import "./globals.css";

export const metadata: Metadata = {
  title: "기로 - 세상의 모든 극한 밸런스게임과 취향 분석 테스트",
  description: "로그인이나 회원가입 없이 즉시 시작하는 실시간 무제한 밸런스게임 플랫폼 '기로'! 음식, 일상, 연애, 상상 등 다양한 카테고리의 극한 양자택일 질문에 투표하고, 연령대별/성별 통계를 통해 다른 사람들과 나의 취향 싱크율을 0초 만에 분석하고 확인해 보세요.",
  icons: {
    icon: "/favicon.ico",
  },
  openGraph: {
    title: "기로 - 세상의 모든 극한 밸런스게임과 취향 분석 테스트",
    description: "로그인이나 회원가입 없이 즉시 시작하는 실시간 무제한 밸런스게임 플랫폼 '기로'! 음식, 일상, 연애, 상상 등 다양한 카테고리의 극한 양자택일 질문에 투표하고, 연령대별/성별 통계를 통해 다른 사람들과 나의 취향 싱크율을 0초 만에 분석하고 확인해 보세요.",
    url: "https://playkiro.kr",
    siteName: "기로",
    images: [
      {
        url: "https://playkiro.kr/og-image.png",
        width: 1200,
        height: 630,
        alt: "기로 밸런스 게임 대표 이미지",
      },
    ],
    locale: "ko_KR",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "기로 - 세상의 모든 극한 밸런스게임과 취향 분석 테스트",
    description: "로그인이나 회원가입 없이 즉시 시작하는 실시간 무제한 밸런스게임 플랫폼 '기로'! 음식, 일상, 연애, 상상 등 다양한 카테고리의 극한 양자택일 질문에 투표하고, 연령대별/성별 통계를 통해 다른 사람들과 나의 취향 싱크율을 0초 만에 분석하고 확인해 보세요.",
    images: ["https://playkiro.kr/og-image.png"],
  },
};

export const viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className="h-full antialiased dark">
      <head>
        <meta name="naver-site-verification" content="aa867b3c75b1169bbf1474f38f3d20d18e83a4bc" />
        
        {/* Favicon package generated by Favicon.im Generator */}
        <link rel="icon" type="image/x-icon" href="/favicon.ico" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
        <link rel="apple-touch-icon" sizes="180x180" href="/favicon-180x180.png" />
        <link rel="icon" type="image/png" sizes="192x192" href="/favicon-192x192.png" />
        <link rel="icon" type="image/png" sizes="512x512" href="/favicon-512x512.png" />
        <meta name="theme-color" content="#ffffff" />

        <link
          rel="stylesheet"
          as="style"
          crossOrigin="anonymous"
          href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/static/pretendard.css"
        />
        {/* Load heavy blocky fonts matching Kiro brand identity */}
        <link
          href="https://fonts.googleapis.com/css2?family=Black+Han+Sans&family=Do+Hyeon&display=swap"
          rel="stylesheet"
        />
        {/* Google AdSense Verification Script */}
        <script
          async
          src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-3522634980237009"
          crossOrigin="anonymous"
        />
        {/* Kakao JavaScript SDK */}
        <script
          src="https://t1.kakaocdn.net/kakao_js_sdk/2.8.1/kakao.min.js"
          integrity="sha384-OL+ylM/iuPLtW5U3XcvLSGhE8JzReKDank5InqlHGWPhb4140/yrBw0bg0y7+C9J"
          crossOrigin="anonymous"
          async
        />
      </head>
      <body className="min-h-full bg-[#080911] text-white antialiased">
        {/* Google Analytics (GA4) Script */}
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-1EQTDJBSD4"
          strategy="afterInteractive"
        />
        <Script id="google-analytics" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-1EQTDJBSD4', { send_page_view: false });
          `}
        </Script>
        <GoogleAnalyticsTracker gaId="G-1EQTDJBSD4" />
        {children}
      </body>
    </html>
  );
}
